version: '3.8'

services:
  n8ntest:
    image: n8nio/n8n:{version}
    container_name: n8ntest
    ports:
      - "15678:5678"
    environment:
      - N8N_DEFAULT_LOCALE=zh-CN
      - N8N_SECURE_COOKIE=false
    volumes:
      - ./editor-ui-dist:/usr/local/lib/node_modules/n8n/node_modules/n8n-editor-ui/dist
    stdin_open: true
    tty: true
    restart: unless-stopped
